sudo : required
language: php

php:
  - 7.1
env:
  global:
    $ROOT=$PWD
before_install:
  - sudo apt-get install libpcre3 libpcre3-dev
  - sudo apt-get install zlib1g-dev

install:
  - wget http://nginx.org/download/nginx-1.13.9.tar.gz
  - tar zxvf nginx-1.13.9.tar.gz
  - cd nginx-1.13.9
  - ./configure --prefix=/home/travis/nginx
  - make && make install
  - export PATH=/home/travis/nginx/sbin:$PATH

script:
  - nginx
